Revert "settings: add CPU info overlay [2/2]"
This reverts commit ec4684354df85a296b83cd529b7c47065c972da9.

ERROR: /home/kevin/CandyTest/frameworks/base/packages/SystemUI/src
/com/android/systemui/BootReceiver.java:44: START_SCREEN_STATE_SER
VICE cannot be resolved or is not a field 
ERROR: /home/kevin/CandyTest/frameworks/base/packages/SystemUI/src
/com/android/systemui/BootReceiver.java:45: com.android.systemui.s
creenstate cannot be resolved to a type

Change-Id: I0bfd714196859cb5d21728fb624b216b95ca7f72